### PR TITLE
Add r/placetux banner

### PR DESCRIPTION
**Pull request by BafDyce**

### CODE REVIEW

**Comment by BafDyce** [comment]
Note: I used gimp for changing the pic and used the default export settings. Hope that was correct.

**Comment by yamhab** [comment]
Can you edit so that it looks like the one currently on r/place (lowercase R for example)?

**Comment by BafDyce** [comment]
The R is currently upper case (and stayed like this for the last half an hour) on r/place. Thats why I changed it to an upper case here as well. Maybe we should discuss this in Matrix

**Comment by Aman9das** [comment]
closing, redo on new image with manjaro and all

**Pull request closed without merging**
