### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Aman9das**

### CODE REVIEW

**Comment by yamhab** [comment]
> _ No description provided. _

What does this add?

**Comment by 10maurycy10** [comment]
Something to the kritta files.

**Comment by 10maurycy10** [comment]
@yamin-shihab

**Comment by yamhab** [comment]
> Something to the kritta files.

Which is...?

**Comment by Aman9das** [comment]
its the source code of my pixel art, with layers and palette and all

**Comment by yamhab** [comment]
Well on Discord, we all agreed to not have any image files other than .png, to avoid confusion and B L O A T. So I'm closing.

**Comment by Aman9das** [comment]
I am from the matrix room,

**Comment by yamhab** [comment]
But should there be a Krita file? I think there should be only .png images, to not confuse people. We already have a palette at root too. It's also conflicting too.

**Pull request merged**
